short_name = "godot"
name = "Godot Engine: Conservatory Edition"
major = 4
minor = 6
patch = 0
status = "stable"
module_config = ""
website = "https://xansworkshop.com/conservatory/blog/site/engine"
docs = "4.6"