short_name = "godot"
name = "Godot Engine: Conservatory Edition"
major = 4
minor = 7
patch = 2
status = "rc"
build = "conservatory_edition"
module_config = ""
website = "https://xansworkshop.com/conservatory/blog/site/engine"
docs = "4.7"
