short_name = "godot"
name = "Godot Engine: Conservatory Edition"
major = 4
minor = 5
patch = 1
status = "stable"
build = "conservatory_edition"
module_config = ""
website = "https://xansworkshop.com/conservatory/blog/site/engine"
docs = "4.5"
